### ISSUE TITLE
awesome! can we have an option to not show/auto close the packing buffer?

### ISSUE THREAD

**Issue by zeltak** [10sr/pack-el#3]
this is really great!

can we have an option to not show/auto close the packing buffer? the remaining split buffer that stays after each unpack is kinda annoying :D 

best and thx!

Z

**Comment by 10sr** [comment]
Thanks for your suggestion!
Sounds nice, I'll try it shortly.

**Comment by 10sr** [comment]
I've merged #4, which adds a new variable `pack-silence`.
Try the latest version with this flag enabled!

**Comment by zeltak** [comment]
works great thx!
