### ISSUE TITLE
file-name-case-insensitive-p: Recursive load

### ISSUE THREAD

**Issue by manuel-uberti** [10sr/pack-el#5]
Hi,

thanks for this package.

I am not sure this is entirely related to `pack`, but this is what I get when I use `pack-dired-dwim` on a file:
```
file-name-case-insensitive-p: Recursive load: "/usr/local/share/emacs/27.0.50/lisp/net/tramp-archive.elc", "/usr/local/share/emacs/27.0.50/lisp/emacs-lisp/debug.elc", "/usr/local/share/emacs/27.0.50/lisp/net/tramp-archive.elc", "/usr/local/share/emacs/27.0.50/lisp/net/tramp-archive.elc", "/usr/local/share/emacs/27.0.50/lisp/net/tramp-archive.elc", "/usr/local/share/emacs/27.0.50/lisp/net/tramp-archive.elc", "/usr/local/share/emacs/27.0.50/lisp/emacs-lisp/cursor-sensor.elc"
Error running timer ‘auto-revert-buffers’: (error "Recursive load" "/usr/local/share/emacs/27.0.50/lisp/net/tramp-archive.elc" "/usr/local/share/emacs/27.0.50/lisp/net/tramp-archive.elc" "/usr/local/share/emacs/27.0.50/lisp/net/tramp-archive.elc" "/usr/local/share/emacs/27.0.50/lisp/net/tramp-archive.elc" "/usr/local/share/emacs/27.0.50/lisp/net/tramp-archive.elc")
```
I am using latest `pack` from MELPA:
```
(use-package pack                       ; Pack and unpack archive files
  :ensure t
  :after dired
  :bind (:map dired-mode-map
              ("P" . pack-dired-dwim))
  :config (setq pack-silence t))
```
And these are some details on my setup you may find useful:
```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2019-01-15

Repository revision: 9530108fbc8bbf1ad5c1debe4b4f21da1238325b
Configured using:
--host=x86_64-debian-linux-gnu --with-modules

Emacs uptime: 2 minutes, 19 seconds
Default font: Iosevka SS08
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04.1 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.3
```
If you need me to do other tests or provide more details, feel free to ask.

**Comment by manuel-uberti** [comment]
It's not happening when I try `pack-dired-dwim` from `emacs -Q`, so it must be related to my configuration.

**Comment by 10sr** [comment]
Thanks!
I want to know whether it still happens when you remove only pack.el related configs.

**Comment by manuel-uberti** [comment]
It only happens when I use `pack.el`, otherwise I never see that error.

**Comment by manuel-uberti** [comment]
I can confirm: if I remove `pack.el` the error never pops up. I tried using `dired-do-compress` from a Dired buffer, and it worked as expected.

It seems to be a conflict with `pack.el` and some code in my Emacs configuration, but I have not been able to track it down so far.

Due the fact that it can be narrowed down to my own configuration, feel free to close the issue if you want. :)

**Comment by manuel-uberti** [comment]
Eventually, I resort to using `dired-do-compress`.

**Comment by 10sr** [comment]
Umm... Sorry I cannot reproduce this issue, and recently do not have much time to look into this...
Please feel free to reopen when you find anything else that might help solve this problem.
Thanks!
